export const mockVehicleTypes = [
  {id: '1', name: '10 Wheeler (24 Ton)', capacity: '24 Ton'},
  {id: '2', name: '12 Wheeler (31 Ton)', capacity: '31 Ton'},
  {id: '3', name: '14 Wheeler (35 Ton)', capacity: '35 Ton'},
  {id: '4', name: '16 Wheeler (40 Ton)', capacity: '40 Ton'},
  {id: '5', name: 'Trailer (49 Ton)', capacity: '49 Ton'},
  {id: '6', name: 'Container (32 Ft)', capacity: '15 Ton'},
  {id: '7', name: 'Open Truck (6 Wheeler)', capacity: '9 Ton'},
  {id: '8', name: 'LCV / Mini Truck', capacity: '3.5 Ton'},
];

export const mockTrucks = [
  {
    id: 'TRK-101',
    vehicleNumber: 'KA 01 AH 5421',
    vehicleTypeId: '1',
    vehicleTypeName: '10 Wheeler (24 Ton)',
    ownership: 'own',
    ownerName: 'Rajesh Transport Co.',
    ownerPhone: '9876543210',
    driverId: 'DRV-01',
    driverName: 'Suresh Yadav',
    driverPhone: '9845012345',
    status: 'on_trip', // 'on_trip' | 'available' | 'maintenance'
    activeTrip: {
      tripId: 'TRP-104',
      lrNumber: 'LR-2026-089',
      partyName: 'Ambuja Cements Ltd',
      route: 'Bangalore → Hyderabad',
      origin: 'Bangalore',
      destination: 'Hyderabad',
      startDate: '28 Aug 2026',
      expectedDelivery: '31 Aug 2026',
      freight: 68500,
    },
    specs: {
      chassisNumber: 'MAT624128N2E12341',
      engineNumber: '497TC92CY812398',
      modelYear: '2023',
      fuelType: 'Diesel',
      odometerKm: '142,500 km',
    },
    documents: [
      {
        id: 'doc-1',
        title: 'Insurance Policy',
        type: 'insurance',
        number: 'POL-ICICI-98231',
        expiryDate: '2026-11-15',
        daysLeft: 77,
        status: 'valid', // valid | expiring_soon | expired
      },
      {
        id: 'doc-2',
        title: 'Fitness Certificate',
        type: 'fitness',
        number: 'FIT-KA-2023-998',
        expiryDate: '2026-09-08',
        daysLeft: 9,
        status: 'expiring_soon',
      },
      {
        id: 'doc-3',
        title: 'National Permit',
        type: 'permit',
        number: 'NP-ALL-INDIA-5541',
        expiryDate: '2027-03-20',
        daysLeft: 202,
        status: 'valid',
      },
      {
        id: 'doc-4',
        title: 'PUC / Pollution',
        type: 'puc',
        number: 'PUC-KA01-2026',
        expiryDate: '2026-09-02',
        daysLeft: 3,
        status: 'expiring_soon',
      },
      {
        id: 'doc-5',
        title: 'Road Tax',
        type: 'tax',
        number: 'TAX-Q3-2026',
        expiryDate: '2026-12-31',
        daysLeft: 123,
        status: 'valid',
      },
    ],
    recentTrips: [
      {
        id: 'TRP-104',
        lrNumber: 'LR-2026-089',
        partyName: 'Ambuja Cements Ltd',
        route: 'Bangalore → Hyderabad',
        date: '28 Aug 2026',
        freight: 68500,
        status: 'In Transit',
      },
      {
        id: 'TRP-098',
        lrNumber: 'LR-2026-074',
        partyName: 'Tata Steel Tubes',
        route: 'Bellary → Chennai',
        date: '14 Aug 2026',
        freight: 52000,
        status: 'Delivered',
      },
      {
        id: 'TRP-085',
        lrNumber: 'LR-2026-061',
        partyName: 'Jindal Steels Ltd',
        route: 'Hospet → Bangalore',
        date: '02 Aug 2026',
        freight: 48000,
        status: 'Delivered',
      },
    ],
    maintenanceHistory: [
      {
        id: 'maint-1',
        category: 'Engine & Oil',
        serviceName: 'Engine Oil & Filter Replacement',
        workshop: 'Tata Authorized Service Center, Nelamangala',
        date: '10 Aug 2026',
        odometerKm: '140,200 km',
        cost: 14500,
      },
      {
        id: 'maint-2',
        category: 'Tyres',
        serviceName: '2 Rear Radial Tyres (Apollo EnduRace)',
        workshop: 'Sri Balaji Tyres & Alignment',
        date: '22 Jul 2026',
        odometerKm: '136,800 km',
        cost: 38000,
      },
    ],
    performance: {
      totalTrips: 42,
      totalRevenue: 2480000,
      dieselExpenses: 940000,
      maintenanceExpenses: 112000,
      netProfit: 1428000,
    },
  },
  {
    id: 'TRK-102',
    vehicleNumber: 'MH 12 RN 8892',
    vehicleTypeId: '2',
    vehicleTypeName: '12 Wheeler (31 Ton)',
    ownership: 'own',
    ownerName: 'Rajesh Transport Co.',
    ownerPhone: '9876543210',
    driverId: 'DRV-02',
    driverName: 'Ramesh Singh',
    driverPhone: '9731234567',
    status: 'available',
    activeTrip: null,
    specs: {
      chassisNumber: 'MAT624128N2E77412',
      engineNumber: '497TC92CY899321',
      modelYear: '2022',
      fuelType: 'Diesel',
      odometerKm: '189,400 km',
    },
    documents: [
      {
        id: 'doc-21',
        title: 'Insurance Policy',
        type: 'insurance',
        number: 'POL-BAJAJ-77123',
        expiryDate: '2026-12-10',
        daysLeft: 102,
        status: 'valid',
      },
      {
        id: 'doc-22',
        title: 'Fitness Certificate',
        type: 'fitness',
        number: 'FIT-MH-2022-441',
        expiryDate: '2027-01-14',
        daysLeft: 137,
        status: 'valid',
      },
      {
        id: 'doc-23',
        title: 'National Permit',
        type: 'permit',
        number: 'NP-ALL-INDIA-9811',
        expiryDate: '2026-10-05',
        daysLeft: 36,
        status: 'valid',
      },
      {
        id: 'doc-24',
        title: 'PUC / Pollution',
        type: 'puc',
        number: 'PUC-MH12-2026',
        expiryDate: '2026-10-25',
        daysLeft: 56,
        status: 'valid',
      },
      {
        id: 'doc-25',
        title: 'Road Tax',
        type: 'tax',
        number: 'TAX-MH-Q3-2026',
        expiryDate: '2026-12-31',
        daysLeft: 123,
        status: 'valid',
      },
    ],
    recentTrips: [
      {
        id: 'TRP-099',
        lrNumber: 'LR-2026-079',
        partyName: 'UltraTech Cement',
        route: 'Pune → Surat',
        date: '20 Aug 2026',
        freight: 74000,
        status: 'Delivered',
      },
    ],
    maintenanceHistory: [
      {
        id: 'maint-11',
        category: 'Brakes & Suspension',
        serviceName: 'Brake Liner & Hub Greasing',
        workshop: 'National Motors Pune',
        date: '05 Aug 2026',
        odometerKm: '187,000 km',
        cost: 9800,
      },
    ],
    performance: {
      totalTrips: 38,
      totalRevenue: 2890000,
      dieselExpenses: 1120000,
      maintenanceExpenses: 89000,
      netProfit: 1681000,
    },
  },
  {
    id: 'TRK-103',
    vehicleNumber: 'AP 07 TX 9012',
    vehicleTypeId: '5',
    vehicleTypeName: 'Trailer (49 Ton)',
    ownership: 'market',
    ownerName: 'Balaji Freight Carriers',
    ownerPhone: '9440112233',
    driverId: 'DRV-03',
    driverName: 'Mohan Reddy',
    driverPhone: '9440556677',
    status: 'on_trip',
    activeTrip: {
      tripId: 'TRP-106',
      lrNumber: 'LR-2026-092',
      partyName: 'JSW Steel Plant',
      route: 'Toranagallu → Mumbai',
      origin: 'Toranagallu',
      destination: 'Mumbai',
      startDate: '29 Aug 2026',
      expectedDelivery: '02 Sep 2026',
      freight: 125000,
    },
    specs: {
      chassisNumber: 'MAT624128N2E55198',
      engineNumber: '497TC92CY811400',
      modelYear: '2021',
      fuelType: 'Diesel',
      odometerKm: '220,100 km',
    },
    documents: [
      {
        id: 'doc-31',
        title: 'Insurance Policy',
        type: 'insurance',
        number: 'POL-NEWINDIA-112',
        expiryDate: '2026-08-25',
        daysLeft: -5,
        status: 'expired',
      },
      {
        id: 'doc-32',
        title: 'Fitness Certificate',
        type: 'fitness',
        number: 'FIT-AP-2021-331',
        expiryDate: '2026-11-20',
        daysLeft: 82,
        status: 'valid',
      },
    ],
    recentTrips: [],
    maintenanceHistory: [],
    performance: {
      totalTrips: 18,
      totalRevenue: 1950000,
      dieselExpenses: 780000,
      maintenanceExpenses: 45000,
      netProfit: 1125000,
    },
  },
  {
    id: 'TRK-104',
    vehicleNumber: 'DL 01 AA 3321',
    vehicleTypeId: '6',
    vehicleTypeName: 'Container (32 Ft)',
    ownership: 'own',
    ownerName: 'Rajesh Transport Co.',
    ownerPhone: '9876543210',
    driverId: 'DRV-04',
    driverName: 'Vikram Sharma',
    driverPhone: '9911223344',
    status: 'maintenance',
    activeTrip: null,
    specs: {
      chassisNumber: 'MAT624128N2E99014',
      engineNumber: '497TC92CY877112',
      modelYear: '2020',
      fuelType: 'Diesel',
      odometerKm: '265,300 km',
    },
    documents: [
      {
        id: 'doc-41',
        title: 'Insurance Policy',
        type: 'insurance',
        number: 'POL-TATA-33211',
        expiryDate: '2027-02-18',
        daysLeft: 172,
        status: 'valid',
      },
      {
        id: 'doc-42',
        title: 'Fitness Certificate',
        type: 'fitness',
        number: 'FIT-DL-2020-001',
        expiryDate: '2026-12-05',
        daysLeft: 97,
        status: 'valid',
      },
    ],
    recentTrips: [],
    maintenanceHistory: [
      {
        id: 'maint-41',
        category: 'Clutch & Transmission',
        serviceName: 'Clutch Plate & Pressure Plate Replacement',
        workshop: 'Delhi Truck Hub, Sanjay Gandhi Transport Nagar',
        date: '27 Aug 2026',
        odometerKm: '265,300 km',
        cost: 26500,
      },
    ],
    performance: {
      totalTrips: 31,
      totalRevenue: 2150000,
      dieselExpenses: 890000,
      maintenanceExpenses: 98000,
      netProfit: 1162000,
    },
  },
];
