<?php  include("adminsession.php");

$dispatch_id = trim(addslashes($_REQUEST['dispatch_id']));
$type = trim(addslashes($_REQUEST['type']));
$otpcode = mt_rand(1000,9999);
 $di_no =	$cmn->getvalfield($connection,"dispatch_entry","di_no","dispatch_id='$dispatch_id'");
 
mysqli_query($connection,"update get_otp set otpcode='$otpcode' ");
if($type=='edit'){

   $msg= "Your otp no  $otpcode ,is generated by $user_name to Edit Entry ";

}
if($type=='del'){

    $msg= "Your otp no  $otpcode , is generated by $user_name to Delete  Entry ";
 
 }
 $url="http://api.iconicsolution.co.in/wapp/api/send?";
$data="apikey=0ac19e01e8804aa3a08d7231c6dea1b9&mobile=9977589000&msg=$msg";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));   
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$result = curl_exec($ch);
var_dump($result);
// $url="http://api.iconicsolution.co.in/wapp/api/send?";
// $data="apikey=fc86f138d94c456ea7fae49bcfddee87&mobile=8871181890&msg=$msg";
// $ch = curl_init();
// curl_setopt($ch, CURLOPT_URL, $url);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));   
// curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
// curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
// $result = curl_exec($ch);
// var_dump($result);

 echo $otpcode;
?> 

