export const routes = {
  auth: 'Auth',
  app: 'App',
  splash: 'Splash',
  welcome: 'Welcome',
  authForm: 'AuthForm',
  //login: 'Login',
  //otp: 'Otp',
  businessSetup: 'BusinessSetup',
  mainTabs: 'MainTabs',
  home: 'Home',
  trips: 'Trips',
  add: 'Add',
  khata: 'Khata',
  more: 'More',
  partiesList: 'PartiesList',
  addParty: 'AddParty',
  selectState: 'SelectState',
  tripsList: 'TripsList',
  addTrip: 'AddTrip',
  tripDetails: 'TripDetails',
  tripProgress: 'TripProgress',
  addLoad: 'AddLoad',
};